"""Deterministic retrieval-index contracts and builders."""

from .contracts import (
    CONTENT_RENDERER_VERSION,
    EMBEDDING_DIMENSION,
    EMBEDDING_VERSION,
    INDEX_VERSION,
    AtomicIndexInput,
    ClaimVersionLineage,
    IndexConfig,
    IndexRecord,
    RelationLineage,
    RetrievalIndexError,
    SessionIndexInput,
    SessionStatementInput,
    SourceSpanLineage,
    TransactionTime,
    ValidTime,
    load_index_config,
)
from .embeddings import DeterministicTokenHashEmbedder, Embedder, normalized_tokens
from .indexing import (
    build_atomic_index_record,
    build_session_index_record,
    render_atomic_content,
    render_session_content,
)
from .repository import (
    IndexBuildRequest,
    IndexPersistenceResult,
    RetrievalIndexRepository,
    RetrievalPersistenceConflict,
    RetrievalPersistenceError,
)
from .query_contracts import (
    EligibilityDecision,
    EligibilityResult,
    QueryPlan,
    RequestedValidTime,
    RetrievalQueryError,
    RetrievalQueryFailure,
    RetrievalQueryRequest,
    parse_retrieval_query_request,
)
from .query_planner import (
    QueryPlannerConfig,
    RetrievalQueryPlanner,
    build_query_plan,
    classify_query,
    load_query_planner_config,
    normalized_query_tokens,
)
from .query_repository import RetrievalQueryRepository, RetrievalQueryRepositoryError

__all__ = [
    "CONTENT_RENDERER_VERSION",
    "EMBEDDING_DIMENSION",
    "EMBEDDING_VERSION",
    "INDEX_VERSION",
    "AtomicIndexInput",
    "ClaimVersionLineage",
    "DeterministicTokenHashEmbedder",
    "Embedder",
    "IndexConfig",
    "IndexBuildRequest",
    "IndexPersistenceResult",
    "IndexRecord",
    "RelationLineage",
    "RetrievalIndexError",
    "RetrievalIndexRepository",
    "RetrievalQueryError",
    "RetrievalQueryFailure",
    "RetrievalQueryPlanner",
    "RetrievalQueryRepository",
    "RetrievalQueryRepositoryError",
    "RetrievalQueryRequest",
    "RetrievalPersistenceConflict",
    "RetrievalPersistenceError",
    "SessionIndexInput",
    "SessionStatementInput",
    "SourceSpanLineage",
    "TransactionTime",
    "ValidTime",
    "EligibilityDecision",
    "EligibilityResult",
    "QueryPlan",
    "QueryPlannerConfig",
    "RequestedValidTime",
    "build_atomic_index_record",
    "build_session_index_record",
    "load_index_config",
    "load_query_planner_config",
    "normalized_tokens",
    "normalized_query_tokens",
    "parse_retrieval_query_request",
    "build_query_plan",
    "classify_query",
    "render_atomic_content",
    "render_session_content",
]
